THIS CUSTOM SCRIPT IS CREATED BY BOTH ME AND KARAN

In [13]:
# imports
import os
import joblib
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.utils.multiclass import unique_labels
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

In [3]:
filename = './Ninapro_DB1.csv'
df = pd.read_csv(filename)
df = df.sample(frac=1,random_state=42)
df.to_csv('./shuffled_data.csv')

In [5]:






# not required column names
cols = ["Unnamed: 0", "stimulus", "restimulus",
        "repetition", "rerepetition", "subject"]

# Models
KNN = KNeighborsClassifier(n_neighbors=5,
                           weights="distance",
                           algorithm="auto",
                           leaf_size=50)

# SVM = SVC(kernel="linear", C=1)

# RNDF = RandomForestClassifier(n_estimators=100,
#                               criterion="log_loss")

# Variables
_X = pd.DataFrame()
_y = pd.Series()
_X_train = pd.DataFrame()
_y_train = pd.Series()
_X_test = pd.DataFrame()
_y_test = pd.Series()


# start script
def _start_(model_name, shuffled_data, chunk_size,  concat: bool = False):
    
    global _X, _y, _X_train, _y_train, _X_test, _y_test

    print(f"\n[+] Training {model_name}")

    # helper function
    def _concat_(_A, a):
        if _A is None:
            _A = a
        else:
            _A = pd.concat([_A, a], ignore_index=True)
        return _A

    # creating the chunk reader
    csv_chunk_reader = pd.read_csv(filepath_or_buffer=shuffled_data,
                                   chunksize=int(chunk_size),
                                   na_filter=False)

    # reading chunk-by-chunk
    for chunk in csv_chunk_reader:
        print("\n[*] Running on new chunk")
        # dropping the columns
        chunk.drop(cols, axis=1, inplace=True)

        # features / labels
        X = chunk.iloc[:, :-1]
        y = chunk.iloc[:, -1]
        print("features:", X.shape)
        print("label:", y.shape)
        print(y.value_counts(sort=True, ascending=True, dropna=False))

        # checking for unique labels
        unique_classes_chunk = unique_labels(y)

        if len(unique_classes_chunk) < 2:
            print("[-] Skipping chunk with only one class.")
            continue

        # train-test splitting
        X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                            test_size=0.2,
                                                            train_size=0.8,
                                                            shuffle=True,
                                                            random_state=98)
        print("Splitted into train(80%) and test (20%)")
        print("X_train:", X_train.shape)
        print("y_train:", y_train.shape)
        print("X_test:", X_test.shape)
        print("y_test:", y_test.shape)

        # fitting into the model
        model_name.fit(X_train, y_train)
        print(f"[+] Fitted model {model_name}")

        # concatenating the features and labels
        if concat:
            _X = _concat_(_X, X)
            _y = _concat_(_y, y)
            _X_train = _concat_(_X_train, X_train)
            _y_train = _concat_(_y_train, _y_train)
            _X_test = _concat_(_X_test, X_test)
            _y_test = _concat_(_y_test, y_test)
            print("[+] Concatenated Chunk")

In [6]:
# save the model(s) to the file(s)
def save_model(_name, file_name: str = "1.joblib"):
    joblib.dump(_name, filename=file_name)
    print(f"[+] {_name} saved to {file_name}")

In [7]:
# starting the training process
CHUNK_SIZE = 1e6

_start_(model_name=KNN,
        shuffled_data='./shuffled_data.csv',
        chunk_size=CHUNK_SIZE,  concat=True)
print("\n[+] KNN trained successfully")
save_model(KNN, "knn_model.joblib")

# _start_(model_name=RNDF,
#         shuffled_data=shuffled_data_filepath,
#         chunk_size=CHUNK_SIZE)
# print("\n[+] Random Forest trained successfully")
# save_model(RNDF, "rndf_model.joblib")

# _start_(model_name=SVM,
#         shuffled_data=shuffled_data_filepath,
#         chunk_size=CHUNK_SIZE)
# print("\n[+] SVM trained successfully")
# save_model(SVM, "svm_model.joblib")


[+] Training KNeighborsClassifier(leaf_size=50, weights='distance')

[*] Running on new chunk
features: (1000000, 33)
label: (1000000,)
exercise
1    218095
2    307731
3    474174
Name: count, dtype: int64
Splitted into train(80%) and test (20%)
X_train: (800000, 33)
y_train: (800000,)
X_test: (200000, 33)
y_test: (200000,)
[+] Fitted model KNeighborsClassifier(leaf_size=50, weights='distance')
[+] Concatenated Chunk


C:\Users\91798\AppData\Local\Temp\ipykernel_18056\129246627.py:36: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  _A = pd.concat([_A, a], ignore_index=True)



[*] Running on new chunk
features: (1000000, 33)
label: (1000000,)
exercise
1    217557
2    308263
3    474180
Name: count, dtype: int64
Splitted into train(80%) and test (20%)
X_train: (800000, 33)
y_train: (800000,)
X_test: (200000, 33)
y_test: (200000,)
[+] Fitted model KNeighborsClassifier(leaf_size=50, weights='distance')
[+] Concatenated Chunk

[*] Running on new chunk
features: (1000000, 33)
label: (1000000,)
exercise
1    218387
2    307967
3    473646
Name: count, dtype: int64
Splitted into train(80%) and test (20%)
X_train: (800000, 33)
y_train: (800000,)
X_test: (200000, 33)
y_test: (200000,)
[+] Fitted model KNeighborsClassifier(leaf_size=50, weights='distance')
[+] Concatenated Chunk

[*] Running on new chunk
features: (1000000, 33)
label: (1000000,)
exercise
1    217321
2    308606
3    474073
Name: count, dtype: int64
Splitted into train(80%) and test (20%)
X_train: (800000, 33)
y_train: (800000,)
X_test: (200000, 33)
y_test: (200000,)
[+] Fitted model KNeighborsClassi

In [8]:
# saving the variables
joblib.dump(_X, "feature.joblib")
joblib.dump(_y, "labels.joblib")
joblib.dump(_X_train, "train_features.joblib")
joblib.dump(_y_train, "train_labels.joblib")
joblib.dump(_X_test, "test_features.joblib")
joblib.dump(_y_test, "test_labels.joblib")

# info
print("features:", _X.shape)
print("labels:", _y.shape)
print("features:", _X_train.shape)
print("labels:", _y_train.shape)
print("test features:", _X_test.shape)
print("test labels:", _y_test.shape)

features: (12553611, 33)
labels: (12553611,)
features: (10042888, 33)
labels: (0,)
test features: (2510723, 33)
test labels: (2510723,)


In [9]:
knn_predicts = KNN.predict(_X_test)
print("KNN predictions:", knn_predicts)

KNN predictions: [2 3 1 ... 3 1 2]


In [10]:
# accuracies
def calc_accuracy(classifier, X, y):
    accuracies = cross_val_score(estimator=classifier, X=X, y=y, cv=10)
    print(accuracies.mean())
    print(accuracies.std())

# confusion matrix
def show_matrix(y_test, y_pred):
    cm = confusion_matrix(y_test, y_pred)
    print(cm)

In [11]:
calc_accuracy(KNN, _X, _y)

ValueError: 
All the 10 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Program Files\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 890, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Program Files\Python311\Lib\site-packages\sklearn\base.py", line 1351, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\sklearn\neighbors\_classification.py", line 238, in fit
    return self._fit(X, y)
           ^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\sklearn\neighbors\_base.py", line 476, in _fit
    X, y = self._validate_data(
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\sklearn\base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\sklearn\utils\validation.py", line 1192, in check_X_y
    X = check_array(
        ^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\sklearn\utils\validation.py", line 951, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\sklearn\utils\_array_api.py", line 521, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\pandas\core\generic.py", line 2083, in __array__
    values = self._values
             ^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\pandas\core\frame.py", line 1046, in _values
    return ensure_wrapped_if_datetimelike(self.values)
                                          ^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\pandas\core\frame.py", line 12281, in values
    return self._mgr.as_array()
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\pandas\core\internals\managers.py", line 1656, in as_array
    arr = self._interleave(dtype=dtype, na_value=na_value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\pandas\core\internals\managers.py", line 1689, in _interleave
    result = np.empty(self.shape, dtype=dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 2.78 GiB for an array with shape (33, 11298249) and data type float64

--------------------------------------------------------------------------------
9 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Program Files\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 890, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Program Files\Python311\Lib\site-packages\sklearn\base.py", line 1351, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\sklearn\neighbors\_classification.py", line 238, in fit
    return self._fit(X, y)
           ^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\sklearn\neighbors\_base.py", line 476, in _fit
    X, y = self._validate_data(
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\sklearn\base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\sklearn\utils\validation.py", line 1192, in check_X_y
    X = check_array(
        ^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\sklearn\utils\validation.py", line 951, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\sklearn\utils\_array_api.py", line 521, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\pandas\core\generic.py", line 2083, in __array__
    values = self._values
             ^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\pandas\core\frame.py", line 1046, in _values
    return ensure_wrapped_if_datetimelike(self.values)
                                          ^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\pandas\core\frame.py", line 12281, in values
    return self._mgr.as_array()
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\pandas\core\internals\managers.py", line 1656, in as_array
    arr = self._interleave(dtype=dtype, na_value=na_value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\site-packages\pandas\core\internals\managers.py", line 1689, in _interleave
    result = np.empty(self.shape, dtype=dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 2.78 GiB for an array with shape (33, 11298250) and data type float64


In [15]:
ac = accuracy_score(_y_test,knn_predicts)
print(ac)

0.9999641537517281


In [12]:
show_matrix(_y_test, knn_predicts)

[[ 546762      28       0]
 [     14  772560       0]
 [     32      16 1191311]]
